### ISSUE TITLE
Fetch Images and show on main page

### ISSUE THREAD

**Issue by bodnarIQ** [D1LL1G4F/Covid_Museum#3]
* [ ] Vytvorit main page, kde sa zobrazia obrazky (zatial mockovane)
  - prvych X obrazkov, na striedacku, na jednej strane obrazok, na druhej popis
* [ ] Vytvorit componentu pre fetchovanie obrazku
* [ ] Vytvorit componentu pre fetchovanie viacerych obrazkov

**Comment by michalovjan** [comment]
IT'S DONE
